
name: Gradle Build
#we need to get this to work
on:
  push:
  pull_request:

jobs:
  build:
##lmao
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: |
          ./gradlew setupDecompWorkspace
          ./gradlew build 
          
      - name: List files
        run: ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lavahack
          path: ./build/libs/*release.jar
